### ISSUE TITLE
I'm trying to use this with npm package and don't fully understand how to use it. Can you please help?

### ISSUE THREAD

**Issue by vedangdanej** [springload/react-iframe-click#1]
What do I import from the react-iframe-click library and how exactly do I use it? Also, I'm not using typescript with my react application. Will this work?

**Comment by holloway** [comment]
Just updated the docs with an example of usage. Let me know if that doesn't work for you.

https://github.com/springload/react-iframe-click#usage

**Comment by holloway** [comment]
TypeScript is always optional in any JavaScript project. You can use it or not.

**Comment by vedangdanej** [comment]
I imported `<Iframe>` from the library and I got this error : 'Module not found: Can't resolve 'react-iframe-click' in 'C:\Users\Microsoft\Desktop\media-gallery\src\Components'.
Then, I installed typescript using the command 'npm install --save typescript', but again I got the same error.
Please, can you help. Sorry, I am very new to using imported typescript libraries. 
Thanks.
Also my react version is 17.0.2

**Comment by holloway** [comment]
Add packages per this documentation https://docs.npmjs.com/downloading-and-installing-packages-locally

eg.

```
npm install react-iframe-click
```

**Comment by vedangdanej** [comment]
I did install it. I installed both react-iframe-click and typescript . I still get the error. Maybe something is not working in the module. Can you check it on your end? This is what the dependencies look like in my package.json file:
```
"dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "antd": "^4.15.4",
    "bootstrap": "^4.6.0",
    "react": "^17.0.2",
    "react-bootstrap": "^1.5.2",
    "react-dom": "^17.0.2",
    "react-iframe-click": "^1.0.2",
    "react-images": "*",
    "react-photo-gallery": "^8.0.0",
    "react-router": "^5.2.0",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "typescript": "^4.2.4",
    "web-vitals": "^1.1.1"
}
```

**Comment by vedangdanej** [comment]
I created a react project and tried to install this package just to be sure that the problem is not with my files. And after running the command ` npm install react-iframe-click` I got this error :
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree        
npm ERR! 
npm ERR! While resolving: test_package@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-iframe-click@1.0.2
npm ERR! node_modules/react-iframe-click
npm ERR!   react-iframe-click@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Microsoft\AppData\Local\npm-cache\eresolve-report.txt for a full report.       

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Microsoft\AppData\Local\npm-cache\_logs\2021-05-04T14_15_18_747Z-debug.log 
```

The problem is definately with the package. If you resolve this, please let me know.
Thanks

**Comment by holloway** [comment]
Ok can you try again now?

It should be version 2.0.2 that you install

**Comment by vedangdanej** [comment]
Thanks, it worked. But I have another problem. I have multiple `<iframes>` on a single page. The onInferredClick gets fired only for one of those iframes. It dosen't get fired after the first one. Can I fix this?

**Comment by holloway** [comment]
I'll look at this in the next few days.

Does it work if you bring focus back to the page, and then click the other iframe?

It's possible that browsers prevent the information needed to infer clicks between iframes.

**Comment by vedangdanej** [comment]
I will try to look into the browser focus and test this. I'm not much
familiar with the 'blur' and 'focus' events in javascript. I will let you
know if it works.
Thanks.

**Comment by vedangdanej** [comment]
I checked if the <Iframe> element registered a click after clicking  anywhere else on the page again and it does. But, I am unable to bring the focus back to the page programatically. I need to automatically bring the focus back to the page after the OnInferredClick function fires off.

**Comment by holloway** [comment]
In the onInferredClick callback you could write something like
(untested)

document.body.focus();

... To move figure back to the parent page

**Comment by vedangdanej** [comment]
I tried both `document.body.focus()` and `document.body.click()`. Both of them don't work. Is there any other workaround for this?

**Comment by Vedang-Danej** [comment]
I used a different approach

**Comment by vedangdanej** [comment]
I used a different approach and it worked. Anyone trying to detect clicks on multiple iframe elements on a single page can refer to this.
https://stackoverflow.com/questions/67359815/how-to-cover-the-thumbnail-of-an-iframe-video-100-to-the-wrapper-in-916-aspect

**Comment by flavicastelo** [comment]
> I created a react project and tried to install this package just to be sure that the problem is not with my files. And after running the command ` npm install react-iframe-click` I got this error :
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree        
> npm ERR! 
> npm ERR! While resolving: test_package@0.1.0
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   react@"^17.0.2" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0" from react-iframe-click@1.0.2
> npm ERR! node_modules/react-iframe-click
> npm ERR!   react-iframe-click@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\Microsoft\AppData\Local\npm-cache\eresolve-report.txt for a full report.       
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Microsoft\AppData\Local\npm-cache\_logs\2021-05-04T14_15_18_747Z-debug.log 
> ```
> 
> The problem is definately with the package. If you resolve this, please let me know. Thanks


I have the same problem
